// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageServer.Another.Common;

namespace MyPackageServer.Another.Test
{
    /// <summary>
    /// DataExportJobRequest
    /// </summary>
    public partial class DataExportJobRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataExportJobRequest" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="format">format</param>
        /// <param name="includeMetadata">includeMetadata (default to false)</param>
        [JsonConstructor]
        public DataExportJobRequest(TypeEnum type, FormatEnum format, Option<bool?> includeMetadata = default)
        {
            Type = type;
            Format = format;
            IncludeMetadataOption = includeMetadata;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataExportJobRequest" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public DataExportJobRequest()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum DataExport for value: dataExport
            /// </summary>
            DataExport = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("dataExport"))
                return TypeEnum.DataExport;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("dataExport"))
                return TypeEnum.DataExport;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.DataExport)
                return "dataExport";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 1,

            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 2
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum value)
        {
            if (value == FormatEnum.Csv)
                return "csv";

            if (value == FormatEnum.Json)
                return "json";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum Format { get; set; }

        /// <summary>
        /// Used to track the state of IncludeMetadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IncludeMetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets IncludeMetadata
        /// </summary>
        [JsonPropertyName("includeMetadata")]
        public bool? IncludeMetadata { get { return this.IncludeMetadataOption; } set { this.IncludeMetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataExportJobRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  IncludeMetadata: ").Append(IncludeMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }


    /// <summary>
    /// A Json converter for type <see cref="DataExportJobRequest" />
    /// </summary>
    public class DataExportJobRequestJsonConverter : JsonConverter<DataExportJobRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="DataExportJobRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DataExportJobRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DataExportJobRequest.TypeEnum?> type = default;
            Option<DataExportJobRequest.FormatEnum?> format = default;
            Option<bool?> includeMetadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<DataExportJobRequest.TypeEnum?>(DataExportJobRequest.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                                format = new Option<DataExportJobRequest.FormatEnum?>(DataExportJobRequest.FormatEnumFromStringOrDefault(formatRawValue));
                            break;
                        case "includeMetadata":
                            includeMetadata = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class DataExportJobRequest.", nameof(type));

            if (!format.IsSet)
                throw new ArgumentException("Property is required for class DataExportJobRequest.", nameof(format));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class DataExportJobRequest.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class DataExportJobRequest.");

            if (includeMetadata.IsSet && includeMetadata.Value == null)
                throw new ArgumentNullException(nameof(includeMetadata), "Property is not nullable for class DataExportJobRequest.");

            return new DataExportJobRequest(type.Value!.Value!, format.Value!.Value!, includeMetadata);
        }

        /// <summary>
        /// Serializes a <see cref="DataExportJobRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataExportJobRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DataExportJobRequest dataExportJobRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dataExportJobRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DataExportJobRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataExportJobRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DataExportJobRequest dataExportJobRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            var typeRawValue = DataExportJobRequest.TypeEnumToJsonValue(dataExportJobRequest.Type);
            writer.WriteString("type", typeRawValue);
            var formatRawValue = DataExportJobRequest.FormatEnumToJsonValue(dataExportJobRequest.Format);
            writer.WriteString("format", formatRawValue);
            if (dataExportJobRequest.IncludeMetadataOption.IsSet)
                writer.WriteBoolean("includeMetadata", dataExportJobRequest.IncludeMetadataOption.Value!.Value);
        }
    }
}
