// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageServer.Another.Common;

namespace MyPackageServer.Another.Test
{
    /// <summary>
    /// Job
    /// </summary>
    public partial class Job
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Job" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="completedAt">completedAt</param>
        /// <param name="recipient">recipient</param>
        /// <param name="subject">subject</param>
        /// <param name="format">format</param>
        /// <param name="downloadUrl">downloadUrl</param>
        [JsonConstructor]
        public Job(Guid id, JobStatus status, DateTimeOffset createdAt, Option<DateTimeOffset?> completedAt = default, Option<string?> recipient = default, Option<string?> subject = default, Option<FormatEnum?> format = default, Option<string?> downloadUrl = default)
        {
            Id = id;
            Type = this.GetType().Name;
            Status = status;
            CreatedAt = createdAt;
            CompletedAtOption = completedAt;
            RecipientOption = recipient;
            SubjectOption = subject;
            FormatOption = format;
            DownloadUrlOption = downloadUrl;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Job" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public Job()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public JobStatus Status { get; set; }

        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 1,

            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 2
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Csv)
                return "csv";

            if (value == FormatEnum.Json)
                return "json";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormatEnum?> FormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The discriminator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public string Type { get; } = default!;

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completedAt")]
        public DateTimeOffset? CompletedAt { get { return this.CompletedAtOption; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Recipient
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RecipientOption { get; private set; }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [JsonPropertyName("recipient")]
        public string? Recipient { get { return this.RecipientOption; } set { this.RecipientOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of DownloadUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DownloadUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets DownloadUrl
        /// </summary>
        [JsonPropertyName("downloadUrl")]
        public string? DownloadUrl { get { return this.DownloadUrlOption; } set { this.DownloadUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Job {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }


    /// <summary>
    /// A Json converter for type <see cref="Job" />
    /// </summary>
    public class JobJsonConverter : JsonConverter<Job>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Job" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Job Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> type = default;
            Option<JobStatus?> status = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<DateTimeOffset?> completedAt = default;
            Option<string?> recipient = default;
            Option<string?> subject = default;
            Option<Job.FormatEnum?> format = default;
            Option<string?> downloadUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<JobStatus?>(JobStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completedAt":
                            completedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "recipient":
                            recipient = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                                format = new Option<Job.FormatEnum?>(Job.FormatEnumFromStringOrDefault(formatRawValue));
                            break;
                        case "downloadUrl":
                            downloadUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(id));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(type));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Job.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Job.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Job.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Job.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Job.");

            if (recipient.IsSet && recipient.Value == null)
                throw new ArgumentNullException(nameof(recipient), "Property is not nullable for class Job.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class Job.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class Job.");

            if (downloadUrl.IsSet && downloadUrl.Value == null)
                throw new ArgumentNullException(nameof(downloadUrl), "Property is not nullable for class Job.");

            return new Job(id.Value!.Value!, status.Value!.Value!, createdAt.Value!.Value!, completedAt, recipient, subject, format, downloadUrl);
        }

        /// <summary>
        /// Serializes a <see cref="Job" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="job"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Job job, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, job, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Job" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="job"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Job job, JsonSerializerOptions jsonSerializerOptions)
        {
            if (job.RecipientOption.IsSet && job.Recipient == null)
                throw new ArgumentNullException(nameof(job.Recipient), "Property is required for class Job.");

            if (job.SubjectOption.IsSet && job.Subject == null)
                throw new ArgumentNullException(nameof(job.Subject), "Property is required for class Job.");

            if (job.DownloadUrlOption.IsSet && job.DownloadUrl == null)
                throw new ArgumentNullException(nameof(job.DownloadUrl), "Property is required for class Job.");

            writer.WriteString("id", job.Id);

            writer.WriteString("type", job.Type);

            var statusRawValue = JobStatusValueConverter.ToJsonValue(job.Status);
            writer.WriteString("status", statusRawValue);

            writer.WriteString("createdAt", job.CreatedAt.ToString(CreatedAtFormat));

            if (job.CompletedAtOption.IsSet)
                if (job.CompletedAtOption.Value != null)
                    writer.WriteString("completedAt", job.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));
                else
                    writer.WriteNull("completedAt");

            if (job.RecipientOption.IsSet)
                writer.WriteString("recipient", job.Recipient);

            if (job.SubjectOption.IsSet)
                writer.WriteString("subject", job.Subject);

            var formatRawValue = Job.FormatEnumToJsonValue(job.FormatOption.Value!.Value);
            writer.WriteString("format", formatRawValue);
            if (job.DownloadUrlOption.IsSet)
                writer.WriteString("downloadUrl", job.DownloadUrl);
        }
    }
}
