// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageClient.ThisIsTest.ManyOf.Common;

namespace MyPackageClient.ThisIsTest.ManyOf.Them
{
    /// <summary>
    /// EmailJobRequest
    /// </summary>
    public partial class EmailJobRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailJobRequest" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="recipient">recipient</param>
        /// <param name="subject">subject</param>
        /// <param name="body">body</param>
        [JsonConstructor]
        public EmailJobRequest(TypeEnum type, string recipient, string subject, Option<string?> body = default)
        {
            Type = type;
            Recipient = recipient;
            Subject = subject;
            BodyOption = body;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailJobRequest" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public EmailJobRequest()
        {
        }


        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("email"))
                return TypeEnum.Email;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email"))
                return TypeEnum.Email;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Email)
                return "email";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [JsonPropertyName("recipient")]
        public string Recipient { get; set; } = default!;

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string Subject { get; set; } = default!;

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private Option<string?> BodyOption { get; set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public string? Body { get { return this.BodyOption; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailJobRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// A Json converter for type <see cref="EmailJobRequest" />
        /// </summary>
        public class EmailJobRequestJsonConverter : JsonConverter<EmailJobRequest>
        {
            /// <summary>
            /// Deserializes json to <see cref="EmailJobRequest" />
            /// </summary>
            /// <param name="utf8JsonReader"></param>
            /// <param name="typeToConvert"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <returns></returns>
            /// <exception cref="JsonException"></exception>
            public override EmailJobRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
            {
                int currentDepth = utf8JsonReader.CurrentDepth;

                if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                    throw new JsonException();

                JsonTokenType startingTokenType = utf8JsonReader.TokenType;

                Option<EmailJobRequest.TypeEnum?> type = default;
                Option<string?> recipient = default;
                Option<string?> subject = default;
                Option<string?> body = default;

                while (utf8JsonReader.Read())
                {
                    if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                        break;

                    if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                        break;

                    if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                    {
                        string? localVarJsonPropertyName = utf8JsonReader.GetString();
                        utf8JsonReader.Read();

                        switch (localVarJsonPropertyName)
                        {
                            case "type":
                                string? typeRawValue = utf8JsonReader.GetString();
                                if (typeRawValue != null)
                                    type = new Option<EmailJobRequest.TypeEnum?>(EmailJobRequest.TypeEnumFromStringOrDefault(typeRawValue));
                                break;
                            case "recipient":
                                recipient = new Option<string?>(utf8JsonReader.GetString()!);
                                break;
                            case "subject":
                                subject = new Option<string?>(utf8JsonReader.GetString()!);
                                break;
                            case "body":
                                body = new Option<string?>(utf8JsonReader.GetString()!);
                                break;
                            default:
                                break;
                        }
                    }
                }

                if (!type.IsSet)
                    throw new ArgumentException("Property is required for class EmailJobRequest.", nameof(type));

                if (!recipient.IsSet)
                    throw new ArgumentException("Property is required for class EmailJobRequest.", nameof(recipient));

                if (!subject.IsSet)
                    throw new ArgumentException("Property is required for class EmailJobRequest.", nameof(subject));

                if (type.IsSet && type.Value == null)
                    throw new ArgumentNullException(nameof(type), "Property is not nullable for class EmailJobRequest.");

                if (recipient.IsSet && recipient.Value == null)
                    throw new ArgumentNullException(nameof(recipient), "Property is not nullable for class EmailJobRequest.");

                if (subject.IsSet && subject.Value == null)
                    throw new ArgumentNullException(nameof(subject), "Property is not nullable for class EmailJobRequest.");

                if (body.IsSet && body.Value == null)
                    throw new ArgumentNullException(nameof(body), "Property is not nullable for class EmailJobRequest.");

                return new EmailJobRequest(type.Value!.Value!, recipient.Value!, subject.Value!, body);
            }

            /// <summary>
            /// Serializes a <see cref="EmailJobRequest" />
            /// </summary>
            /// <param name="writer"></param>
            /// <param name="emailJobRequest"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <exception cref="NotImplementedException"></exception>
            public override void Write(Utf8JsonWriter writer, EmailJobRequest emailJobRequest, JsonSerializerOptions jsonSerializerOptions)
            {
                writer.WriteStartObject();

                WriteProperties(writer, emailJobRequest, jsonSerializerOptions);
                writer.WriteEndObject();
            }

            /// <summary>
            /// Serializes the properties of <see cref="EmailJobRequest" />
            /// </summary>
            /// <param name="writer"></param>
            /// <param name="emailJobRequest"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <exception cref="NotImplementedException"></exception>
            public void WriteProperties(Utf8JsonWriter writer, EmailJobRequest emailJobRequest, JsonSerializerOptions jsonSerializerOptions)
            {
                if (emailJobRequest.Recipient == null)
                    throw new ArgumentNullException(nameof(emailJobRequest.Recipient), "Property is required for class EmailJobRequest.");

                if (emailJobRequest.Subject == null)
                    throw new ArgumentNullException(nameof(emailJobRequest.Subject), "Property is required for class EmailJobRequest.");

                if (emailJobRequest.BodyOption.IsSet && emailJobRequest.Body == null)
                    throw new ArgumentNullException(nameof(emailJobRequest.Body), "Property is required for class EmailJobRequest.");

                var typeRawValue = EmailJobRequest.TypeEnumToJsonValue(emailJobRequest.Type);
                writer.WriteString("type", typeRawValue);
                writer.WriteString("recipient", emailJobRequest.Recipient);

                writer.WriteString("subject", emailJobRequest.Subject);

                if (emailJobRequest.BodyOption.IsSet)
                writer.WriteString("body", emailJobRequest.Body);
            }
        }
    }
}
