// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageClient.ThisIsTest.ManyOf.Them.Common;

namespace MyPackageClient.ThisIsTest.ManyOf.Them.Models
{
    /// <summary>
    /// NotificationTarget
    /// </summary>
    public partial class NotificationTarget
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationTarget" /> class.
        /// </summary>
        /// <param name="emailTarget"></param>
        /// <param name="webhookTarget"></param>
        public NotificationTarget(Option<EmailTarget?> emailTarget, Option<WebhookTarget?> webhookTarget)
        {
            EmailTargetOption = emailTarget;
            WebhookTargetOption = webhookTarget;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationTarget" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public NotificationTarget()
        {
        }


        /// <summary>
        /// Used to track the state of EmailTarget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EmailTarget?> EmailTargetOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailTarget
        /// </summary>
        public EmailTarget? EmailTarget { get { return this.EmailTargetOption; } set { this.EmailTargetOption = new(value); } }

        /// <summary>
        /// Used to track the state of WebhookTarget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<WebhookTarget?> WebhookTargetOption { get; private set; }

        /// <summary>
        /// Gets or Sets WebhookTarget
        /// </summary>
        public WebhookTarget? WebhookTarget { get { return this.WebhookTargetOption; } set { this.WebhookTargetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationTarget {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }


    /// <summary>
    /// A Json converter for type <see cref="NotificationTarget" />
    /// </summary>
    public class NotificationTargetJsonConverter : JsonConverter<NotificationTarget>
    {
        /// <summary>
        /// Deserializes json to <see cref="NotificationTarget" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NotificationTarget Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            EmailTarget? emailTarget = default;
            WebhookTarget? webhookTarget = default;

            Utf8JsonReader utf8JsonReaderAnyOf = utf8JsonReader;
            while (utf8JsonReaderAnyOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (utf8JsonReaderAnyOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderAnyOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderEmailTarget = utf8JsonReader;
                    ClientUtils.TryDeserialize<EmailTarget?>(ref utf8JsonReaderEmailTarget, jsonSerializerOptions, out emailTarget);

                    Utf8JsonReader utf8JsonReaderWebhookTarget = utf8JsonReader;
                    ClientUtils.TryDeserialize<WebhookTarget?>(ref utf8JsonReaderWebhookTarget, jsonSerializerOptions, out webhookTarget);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            Option<EmailTarget?> emailTargetParsedValue = emailTarget == null
                ? default
                : new Option<EmailTarget?>(emailTarget);
            Option<WebhookTarget?> webhookTargetParsedValue = webhookTarget == null
                ? default
                : new Option<WebhookTarget?>(webhookTarget);

            return new NotificationTarget(emailTargetParsedValue, webhookTargetParsedValue);
        }

        /// <summary>
        /// Serializes a <see cref="NotificationTarget" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationTarget"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NotificationTarget notificationTarget, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            if (notificationTarget.EmailTargetOption.IsSet && notificationTarget.EmailTargetOption.Value != null)
            {
                EmailTargetJsonConverter emailTargetJsonConverter = (EmailTargetJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(notificationTarget.EmailTargetOption.Value.GetType()));
                emailTargetJsonConverter.WriteProperties(writer, notificationTarget.EmailTargetOption.Value, jsonSerializerOptions);
            }

            if (notificationTarget.WebhookTargetOption.IsSet && notificationTarget.WebhookTargetOption.Value != null)
            {
                WebhookTargetJsonConverter webhookTargetJsonConverter = (WebhookTargetJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(notificationTarget.WebhookTargetOption.Value.GetType()));
                webhookTargetJsonConverter.WriteProperties(writer, notificationTarget.WebhookTargetOption.Value, jsonSerializerOptions);
            }

            WriteProperties(writer, notificationTarget, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NotificationTarget" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationTarget"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NotificationTarget notificationTarget, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
