// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageClient.ThisIsTest.ManyOf.Common;

namespace MyPackageClient.ThisIsTest.ManyOf.Them
{
    /// <summary>
    /// HealthCheck200Response
    /// </summary>
    public partial class HealthCheck200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthCheck200Response" /> class.
        /// </summary>
        /// <param name="status">status</param>
        [JsonConstructor]
        public HealthCheck200Response(Option<string?> status = default)
        {
            StatusOption = status;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthCheck200Response" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public HealthCheck200Response()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>ok</example> */
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthCheck200Response {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }


    /// <summary>
    /// A Json converter for type <see cref="HealthCheck200Response" />
    /// </summary>
    public class HealthCheck200ResponseJsonConverter : JsonConverter<HealthCheck200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="HealthCheck200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HealthCheck200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class HealthCheck200Response.");

            return new HealthCheck200Response(status);
        }

        /// <summary>
        /// Serializes a <see cref="HealthCheck200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthCheck200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HealthCheck200Response healthCheck200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, healthCheck200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HealthCheck200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthCheck200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HealthCheck200Response healthCheck200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (healthCheck200Response.StatusOption.IsSet && healthCheck200Response.Status == null)
                throw new ArgumentNullException(nameof(healthCheck200Response.Status), "Property is required for class HealthCheck200Response.");

            if (healthCheck200Response.StatusOption.IsSet)
                writer.WriteString("status", healthCheck200Response.Status);
        }
    }
}
