// <auto-generated>
/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using MyPackageServer.Another.Common;

namespace MyPackageServer.Another.Test
{
    /// <summary>
    /// DataExportJob
    /// </summary>
    public partial class DataExportJob
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataExportJob" /> class.
        /// </summary>
        /// <param name="format">format</param>
        /// <param name="downloadUrl">downloadUrl</param>
        [JsonConstructor]
        public DataExportJob(Option<FormatEnum?> format = default, Option<string?> downloadUrl = default)
        {
            FormatOption = format;
            DownloadUrlOption = downloadUrl;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataExportJob" /> class.
        /// Empty to allow for object initialization syntax.
        /// </summary>
        public DataExportJob()
        {
        }


        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 1,

            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 2
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("json"))
                return FormatEnum.Json;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Csv)
                return "csv";

            if (value == FormatEnum.Json)
                return "json";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private Option<FormatEnum?> FormatOption { get; set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Used to track the state of DownloadUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private Option<string?> DownloadUrlOption { get; set; }

        /// <summary>
        /// Gets or Sets DownloadUrl
        /// </summary>
        [JsonPropertyName("downloadUrl")]
        public string? DownloadUrl { get { return this.DownloadUrlOption; } set { this.DownloadUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataExportJob {\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// A Json converter for type <see cref="DataExportJob" />
        /// </summary>
        public class DataExportJobJsonConverter : JsonConverter<DataExportJob>
        {
            /// <summary>
            /// Deserializes json to <see cref="DataExportJob" />
            /// </summary>
            /// <param name="utf8JsonReader"></param>
            /// <param name="typeToConvert"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <returns></returns>
            /// <exception cref="JsonException"></exception>
            public override DataExportJob Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
            {
                int currentDepth = utf8JsonReader.CurrentDepth;

                if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                    throw new JsonException();

                JsonTokenType startingTokenType = utf8JsonReader.TokenType;

                Option<DataExportJob.FormatEnum?> format = default;
                Option<string?> downloadUrl = default;

                while (utf8JsonReader.Read())
                {
                    if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                        break;

                    if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                        break;

                    if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                    {
                        string? localVarJsonPropertyName = utf8JsonReader.GetString();
                        utf8JsonReader.Read();

                        switch (localVarJsonPropertyName)
                        {
                            case "format":
                                string? formatRawValue = utf8JsonReader.GetString();
                                if (formatRawValue != null)
                                    format = new Option<DataExportJob.FormatEnum?>(DataExportJob.FormatEnumFromStringOrDefault(formatRawValue));
                                break;
                            case "downloadUrl":
                                downloadUrl = new Option<string?>(utf8JsonReader.GetString()!);
                                break;
                            default:
                                break;
                        }
                    }
                }

                if (format.IsSet && format.Value == null)
                    throw new ArgumentNullException(nameof(format), "Property is not nullable for class DataExportJob.");

                if (downloadUrl.IsSet && downloadUrl.Value == null)
                    throw new ArgumentNullException(nameof(downloadUrl), "Property is not nullable for class DataExportJob.");

                return new DataExportJob(format, downloadUrl);
            }

            /// <summary>
            /// Serializes a <see cref="DataExportJob" />
            /// </summary>
            /// <param name="writer"></param>
            /// <param name="dataExportJob"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <exception cref="NotImplementedException"></exception>
            public override void Write(Utf8JsonWriter writer, DataExportJob dataExportJob, JsonSerializerOptions jsonSerializerOptions)
            {
                writer.WriteStartObject();

                WriteProperties(writer, dataExportJob, jsonSerializerOptions);
                writer.WriteEndObject();
            }

            /// <summary>
            /// Serializes the properties of <see cref="DataExportJob" />
            /// </summary>
            /// <param name="writer"></param>
            /// <param name="dataExportJob"></param>
            /// <param name="jsonSerializerOptions"></param>
            /// <exception cref="NotImplementedException"></exception>
            public void WriteProperties(Utf8JsonWriter writer, DataExportJob dataExportJob, JsonSerializerOptions jsonSerializerOptions)
            {
                if (dataExportJob.DownloadUrlOption.IsSet && dataExportJob.DownloadUrl == null)
                    throw new ArgumentNullException(nameof(dataExportJob.DownloadUrl), "Property is required for class DataExportJob.");

                var formatRawValue = DataExportJob.FormatEnumToJsonValue(dataExportJob.FormatOption.Value!.Value);
                writer.WriteString("format", formatRawValue);
                if (dataExportJob.DownloadUrlOption.IsSet)
                writer.WriteString("downloadUrl", dataExportJob.DownloadUrl);
            }
        }
    }
}
