/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MyPackageServer.Another.Models;

namespace MyPackageServer.Another.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class HealthApiController : ControllerBase
    { 
        /// <summary>
        /// Health check
        /// </summary>
        /// <response code="200">Service is healthy</response>
        [HttpGet]
        [Route("/health")]
        [ProducesResponseType(statusCode: 200, type: typeof(HealthCheck200Response))]
        public abstract IActionResult HealthCheck();
    }
}
