/*
 * Job Processing API
 *
 * API for submitting and tracking background jobs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace MyPackageServer.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class HealthCheck200Response 
    {
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>ok</example> */
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string? Status { get; set; } = null!;

    }
}
